version: '3.5'
services:
  ots-share-build:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ots-share-build
    volumes:
      - .:/app
    logging:
      driver: json-file

  ots-share-run:
    build:
      context: .
    container_name: ots-share-run
    environment:
      - DEV_PORT=${DEV_PORT:-9898}
      - DB_URL=mongodb://ots-share-mongo-local/ots-share
      - PURGE_TRIGGER_INTERVAL=60000
    command: sleep infinity
    ports:
      - '${SERVER_PORT:-8282}:80'
      - '${DEV_PORT:-9898}:${DEV_PORT:-9898}'
    volumes:
      - .:/app
    logging:
      driver: json-file
    depends_on:
      - ots-share-mongo-local
    links:
      - ots-share-mongo-local

  ots-share-run-no-db:
    build:
      context: .
    container_name: ots-share-run-db
    environment:
      # - DB_URL=${DB_URL:-mongodb://ots-share-mongo-local/ots-share}
      - DB_URL=
      - DEV_PORT=${DEV_PORT:-9898}
      - PURGE_TRIGGER_INTERVAL=60000
    command: sleep infinity
    ports:
      - '${SERVER_PORT:-8282}:80'
      - '${DEV_PORT:-9898}:${DEV_PORT:-9898}'
    volumes:
      - .:/app
    logging:
      driver: json-file

  ots-share-mongo-local:
    image: mongo:4.2
    container_name: ots-share-mongo-local
    ports:
      - '27017:27017'